import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar.jsx";
import { Inter } from "@next/font/google";
import Header from "../components/header.jsx";
import Services from "../components/services.jsx";
import Package from "../components/package.jsx";
import Explore from "../components/explore.jsx";
import Register from "../components/register.jsx";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" min-h-screen w-[1240px] mx-auto">
        <nav>
          <Navbar />
        </nav>

        <header className="mt-7 ">
          <Header />
        </header>

        <main className="">
          <div className="">
            <section className="mt-28">
              <Services />
            </section>
            <section className="mt-28">
              <Package />
            </section>
            <section className="mt-28">
              <Explore />
            </section>
            <section className="mt-28">
              <Register />
            </section>
          </div>
        </main>
      </div>
      <footer className="bg-slate-800 w-full h-96 text-slate-50 mt-32">
        <p>asd</p>
        <Image src={"/gooutIcon.jpg"} alt="icon" width={200} height={200} />
      </footer>
    </>
  );
}
