import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/navbar.jsx";
import { Inter } from "@next/font/google";
import Header from "../components/header.jsx";
import Services from "../components/services.jsx";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" min-h-screen w-[1240px] mx-auto">
        <nav>
          <Navbar />
        </nav>

        <header className="mt-7 ">
          <Header />
        </header>

        <main className="min-h-screen">
          <div className="">
            <section className="mt-28">
              <Services />
            </section>
            <section></section>
            <section></section>
          </div>
        </main>
      </div>
    </>
  );
}
